In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [4]:
grades = np.array([[79, 74, 94, 88, 72, 93, 84],
         [70, 70, 70, 70, 70, 70, 70],
         [75, 72, 70, 87, 80, 85, 80]])

In [5]:
grades

array([[79, 74, 94, 88, 72, 93, 84],
       [70, 70, 70, 70, 70, 70, 70],
       [75, 72, 70, 87, 80, 85, 80]])

In [6]:
weights = np.array([3, 3, 3, 3, 3, 3, 1])

In [7]:
weights

array([3, 3, 3, 3, 3, 3, 1])

In [8]:
np.dot(grades, weights)

array([1584, 1330, 1487])