In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.random.randn(100)

In [3]:
A

array([-5.99521150e-01,  2.39021923e-01, -5.97821952e-01, -8.10688411e-01,
        2.91189314e-01,  1.51428639e+00, -6.81371533e-01, -1.08625182e+00,
        2.53475027e-01,  3.76889939e-01, -1.84977935e-01, -1.21215537e-01,
        4.14649402e-01,  1.94122551e+00,  8.88462945e-01,  2.79656233e-01,
       -6.73614329e-01, -1.12812929e+00, -1.50969242e+00, -1.52079159e+00,
        2.13406114e+00,  1.58346491e+00, -7.28354270e-01,  9.04138775e-01,
        8.04315725e-01,  8.84093237e-01, -1.52881399e+00,  4.14225454e-01,
        4.40212433e-01, -9.87297534e-01, -1.58512385e+00,  9.06686847e-01,
       -6.03217657e-01,  2.82202683e-02, -2.97023398e+00,  1.14683563e+00,
        1.58129365e+00,  1.49637825e+00,  7.04473551e-01, -6.60535402e-01,
        3.82700275e-01, -1.22875787e+00, -2.28143319e-01, -5.55894800e-01,
        8.06389481e-01,  9.36086026e-01,  7.46872415e-01, -7.76627748e-01,
        3.10781675e-01,  1.50966533e+00, -3.52143200e-01, -1.38410823e+00,
        7.45856919e-02,  

In [5]:
A = 10*A + 50

In [6]:
A

array([44.0047885 , 52.39021923, 44.02178048, 41.89311589, 52.91189314,
       65.14286394, 43.18628467, 39.13748183, 52.53475027, 53.76889939,
       48.15022065, 48.78784463, 54.14649402, 69.4122551 , 58.88462945,
       52.79656233, 43.26385671, 38.71870714, 34.90307585, 34.79208405,
       71.34061135, 65.83464911, 42.7164573 , 59.04138775, 58.04315725,
       58.84093237, 34.71186008, 54.14225454, 54.40212433, 40.12702466,
       34.14876154, 59.06686847, 43.96782343, 50.28220268, 20.29766018,
       61.46835628, 65.81293649, 64.9637825 , 57.04473551, 43.39464598,
       53.82700275, 37.71242131, 47.71856681, 44.441052  , 58.06389481,
       59.36086026, 57.46872415, 42.23372252, 53.10781675, 65.09665327,
       46.478568  , 36.15891773, 50.74585692, 68.69724154, 54.17747208,
       42.43806912, 40.30644203, 50.95481765, 43.11535466, 40.85792852,
       32.37347704, 48.16111126, 50.03452089, 38.31015255, 44.64624872,
       36.19273175, 48.24272501, 61.5395952 , 41.35887293, 32.63

In [7]:
A.shape

(100,)

In [12]:
A.shape = (5, 20)

In [13]:
A

array([[44.0047885 , 52.39021923, 44.02178048, 41.89311589, 52.91189314,
        65.14286394, 43.18628467, 39.13748183, 52.53475027, 53.76889939,
        48.15022065, 48.78784463, 54.14649402, 69.4122551 , 58.88462945,
        52.79656233, 43.26385671, 38.71870714, 34.90307585, 34.79208405],
       [71.34061135, 65.83464911, 42.7164573 , 59.04138775, 58.04315725,
        58.84093237, 34.71186008, 54.14225454, 54.40212433, 40.12702466,
        34.14876154, 59.06686847, 43.96782343, 50.28220268, 20.29766018,
        61.46835628, 65.81293649, 64.9637825 , 57.04473551, 43.39464598],
       [53.82700275, 37.71242131, 47.71856681, 44.441052  , 58.06389481,
        59.36086026, 57.46872415, 42.23372252, 53.10781675, 65.09665327,
        46.478568  , 36.15891773, 50.74585692, 68.69724154, 54.17747208,
        42.43806912, 40.30644203, 50.95481765, 43.11535466, 40.85792852],
       [32.37347704, 48.16111126, 50.03452089, 38.31015255, 44.64624872,
        36.19273175, 48.24272501, 61.5395952 , 4

In [20]:
A.shape = (100, 1)

In [21]:
A

array([[44.0047885 ],
       [52.39021923],
       [44.02178048],
       [41.89311589],
       [52.91189314],
       [65.14286394],
       [43.18628467],
       [39.13748183],
       [52.53475027],
       [53.76889939],
       [48.15022065],
       [48.78784463],
       [54.14649402],
       [69.4122551 ],
       [58.88462945],
       [52.79656233],
       [43.26385671],
       [38.71870714],
       [34.90307585],
       [34.79208405],
       [71.34061135],
       [65.83464911],
       [42.7164573 ],
       [59.04138775],
       [58.04315725],
       [58.84093237],
       [34.71186008],
       [54.14225454],
       [54.40212433],
       [40.12702466],
       [34.14876154],
       [59.06686847],
       [43.96782343],
       [50.28220268],
       [20.29766018],
       [61.46835628],
       [65.81293649],
       [64.9637825 ],
       [57.04473551],
       [43.39464598],
       [53.82700275],
       [37.71242131],
       [47.71856681],
       [44.441052  ],
       [58.06389481],
       [59

In [22]:
A.reshape(5, 20)

array([[44.0047885 , 52.39021923, 44.02178048, 41.89311589, 52.91189314,
        65.14286394, 43.18628467, 39.13748183, 52.53475027, 53.76889939,
        48.15022065, 48.78784463, 54.14649402, 69.4122551 , 58.88462945,
        52.79656233, 43.26385671, 38.71870714, 34.90307585, 34.79208405],
       [71.34061135, 65.83464911, 42.7164573 , 59.04138775, 58.04315725,
        58.84093237, 34.71186008, 54.14225454, 54.40212433, 40.12702466,
        34.14876154, 59.06686847, 43.96782343, 50.28220268, 20.29766018,
        61.46835628, 65.81293649, 64.9637825 , 57.04473551, 43.39464598],
       [53.82700275, 37.71242131, 47.71856681, 44.441052  , 58.06389481,
        59.36086026, 57.46872415, 42.23372252, 53.10781675, 65.09665327,
        46.478568  , 36.15891773, 50.74585692, 68.69724154, 54.17747208,
        42.43806912, 40.30644203, 50.95481765, 43.11535466, 40.85792852],
       [32.37347704, 48.16111126, 50.03452089, 38.31015255, 44.64624872,
        36.19273175, 48.24272501, 61.5395952 , 4

In [24]:
A = A.reshape(5, 20)

In [25]:
A

array([[44.0047885 , 52.39021923, 44.02178048, 41.89311589, 52.91189314,
        65.14286394, 43.18628467, 39.13748183, 52.53475027, 53.76889939,
        48.15022065, 48.78784463, 54.14649402, 69.4122551 , 58.88462945,
        52.79656233, 43.26385671, 38.71870714, 34.90307585, 34.79208405],
       [71.34061135, 65.83464911, 42.7164573 , 59.04138775, 58.04315725,
        58.84093237, 34.71186008, 54.14225454, 54.40212433, 40.12702466,
        34.14876154, 59.06686847, 43.96782343, 50.28220268, 20.29766018,
        61.46835628, 65.81293649, 64.9637825 , 57.04473551, 43.39464598],
       [53.82700275, 37.71242131, 47.71856681, 44.441052  , 58.06389481,
        59.36086026, 57.46872415, 42.23372252, 53.10781675, 65.09665327,
        46.478568  , 36.15891773, 50.74585692, 68.69724154, 54.17747208,
        42.43806912, 40.30644203, 50.95481765, 43.11535466, 40.85792852],
       [32.37347704, 48.16111126, 50.03452089, 38.31015255, 44.64624872,
        36.19273175, 48.24272501, 61.5395952 , 4